services:
  rust-warp:
    build: ./fast-test-rust
    container_name: rust-warp
    restart: unless-stopped
  rust-warp-nginx:
    build: ./nginx
    container_name: rust-warp-nginx
    restart: unless-stopped
    ports:
      - "80:80"
    depends_on:
      - rust-warp